set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(AARCH64_TOOLCHAIN_ROOT /data/yangrongzhao/gcc-arm-9.2-2019.12-x86_64-aarch64-none-linux-gnu)
set(CMAKE_C_COMPILER ${AARCH64_TOOLCHAIN_ROOT}/bin/aarch64-none-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER ${AARCH64_TOOLCHAIN_ROOT}/bin/aarch64-none-linux-gnu-g++)

set(CMAKE_FIND_ROOT_PATH ${AARCH64_TOOLCHAIN_ROOT}/aarch64-none-linux-gnu)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
